config/routes.rb
Rails.application.routes.draw do
  get 'reports/consolidated_report_selection'
  post 'reports/consolidated_report'
  get 'reports/index_marks'
  post 'reports/generate_index_pdf'

  resources :choices
  resources :programmes
  resources :boards, shallow: true do
    resources :streams do
      resources :stream_subjects
    end
  end
  resources :guardians
  resources :occupations
  resources :qualifications
  resources :countries, shallow: true do
    resources :states do
      resources :districts
    end
  end
  resources :reservation_categories do
    resources :castes
  end
  resources :registration_forms
  resources :registration_steps
  resources :students

  get '/login' => 'sessions#new', as: :root
  get '/auth/:provider/callback' => 'sessions#create'
  post '/transaction/ccavRequestHandler'=> 'sessions#ccavRequestHandler'
  post '/transaction/ccavResponseHandler'=> 'sessions#ccavResponseHandler'
  delete '/auth/logout' => 'sessions#destroy'

  namespace :dashboard do
    get 'index'
    match 'instructions', via: [:get, :post]
    get 'personal'
    get 'address'
    get 'guardian'
    get 'weightages'
    get 'education'
    get 'payment'
    get 'marks'
    get 'choices'
    get 'submission'
    get 'photo_upload'
    get 'generate_application_pdf'
    get 'submission_done'
    get 'phase_completed'
    get 'update_menu'
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :streams
end

app/models/caste.rb
class Caste < ActiveRecord::Base
  belongs_to :reservation_category
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :student
  belongs_to :programme
end

app/models/configurator.rb
class Configurator < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :state

  def to_s
    self.name
  end
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  belongs_to :student
  belongs_to :qualification
  belongs_to :occupation
  belongs_to :country
  belongs_to :state
  belongs_to :district

  before_validation :check_if_same_address

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.#{field} = self.student.#{field}")
        end
      end
    end
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :stream_subject
  belongs_to :mark
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/programme.rb
class Programme < ActiveRecord::Base
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :districts
  belongs_to :country
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :stream_subjects
  belongs_to :board
  has_many :choices
end

app/models/stream_subject.rb
class StreamSubject < ActiveRecord::Base
  belongs_to :stream
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :registration_form
  belongs_to :nationality, foreign_key: "nationality_id", class_name: "Country"
  has_one :guardian
  belongs_to :reservation_category
  belongs_to :caste
  belongs_to :state
  belongs_to :district
  belongs_to :country
  belongs_to :comm_state, foreign_key: "comm_state_id", class_name: "State"
  belongs_to :comm_district, foreign_key: "comm_district_id", class_name: "District"
  belongs_to :board
  belongs_to :stream
  mount_uploader :profile_image, ImageUploader

  before_validation :check_if_same_address

  def subject_params=(subject_params)
    subject_params.each do |mark_details|
      mark = mark_details[1]
      unless mark[:score] == 0
        @mark = Mark.where(student_id: self.id, subject_position: mark_details[0]).first
        if @mark
          @mark.update(score: mark[:score], stream_subject_id: mark[:stream_subject_id])
        else
          Mark.create(student_id: self.id, stream_subject_id: mark[:stream_subject_id], score: mark[:score], subject_position:mark_details[0])
        end
      end
    end
  end

  def choice_params=(choice_params)
    choice_params.each do |choice|
      preference_no = choice[0].gsub("choice_", "").to_i
      programme_id = choice[1]

      @choice = Choice.where(preference: preference_no, student_id: self.id).first
      if @choice
        @choice.update(programme_id: programme_id)
      else
        Choice.create(preference: preference_no, student_id: self.id, programme_id: programme_id)
      end
    end
  end

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.comm_#{field} = self.#{field}")
        end
      end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  # def instructions
  #   if request.post?
  #     @origin_step = RegistrationStep.find_by_name('Instructions')
  #     @registration_form = current_user.registration_form
  #     unless @registration_form.instructions_read
  #       @registration_form.increment(:current_step)
  #       @registration_form.update(instructions_read: true)
  #     end
  #     render :proceed2_next
  #   end
  # end

  def personal
  end

  def address
  end

  def guardian
  end

  def weightages
  end

  def education
  end

  def marks
  end

  def choices
  end

  def submission
  end

  def submission_done
    current_user.update(submission_done: true)
    current_user.registration_form.update(current_step: 7)
    flash[:notice] = "You have successfully completed registration! Please visit us back when rank lists are published! "
    redirect_to dashboard_index_url
  end

  def phase_completed
  end

  def update_menu
  end

  def generate_index_pdf
    @programmes = []
    @choices = []
    Programme.where(disabled: false).order(:name).each do |prog|
      next if prog.indexing_rules.nil?
      @programmes << prog
      @choices << Choice.select(:student_id, :index_mark).where(programme_id: prog.id).order(index_mark: :desc)
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/castes_helper.rb
module CastesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def proceed2_step
    if instance_saved
      if @current_step == from - 1
        form = RegistrationForm.find_by_student_id(@student)
        @current_step = form.current_step = form.current_step + 1
        form.current_step = form.current_step + 1 if @current_step == 7
        form.save
      end
    end

    render :proceed2_next
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/dashboard/_payment.erb
<% if current_user.email == "kevin.madhu@gmail.com" || current_user.email == "fareed.tpm@gmail.com" %>
  <% amount = 1 %>
<% elsif (current_user.reservation_category_id == 2 || current_user.reservation_category_id == 3) %>
  <% amount = 110 %>
<% else %>
  <% amount = 160 %>
<% end %>

<form method="POST" name="customerData" action="/transaction/ccavRequestHandler">
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
  <input type="hidden" name="merchant_id" value="<%= Rails.application.config.x.ccavenue['merchant_id'] %>"/>
  <input type="hidden" name="order_id" value="<%= current_user.id %>"/>
  <input type="hidden" name="amount" value="<%= amount %>"/></td>
  <input type="hidden" name="currency" value="INR"/>
  <input type="hidden" name="redirect_url" value="http://mesmampadadmission.in/transaction/ccavResponseHandler"/></td>
  <input type="hidden" name="cancel_url" value="http://mesmampadadmission.in/transaction/ccavResponseHandler"/></td>
  <input type="hidden" name="language" value="EN"/>
  <input type="hidden" name="billing_name" value="<%= current_user.name %>"/>
  <input type="hidden" name="billing_email" value="<%= current_user.email %>"/>
  <input type="hidden" name="integration_type" value="iframe_normal"/>
  <input type="hidden" name="billing_name" value="<%= current_user.name %>"/>
  <input type="hidden" name="billing_address" value="<%= current_user.address_line1 %>"/>
  <input type="hidden" name="billing_city" value="<%= current_user.address_line2 %>"/>
  <input type="hidden" name="billing_state" value="<%= current_user.state.name %>"/>
  <input type="hidden" name="billing_zip" value="<%= current_user.pincode %>"/>
  <input type="hidden" name="billing_country" value="<%= current_user.country.name %>"/>
  <input type="hidden" name="billing_tel" value="<%= current_user.mobile_no %>"/>
  <input type="hidden" name="billing_email" value="<%= current_user.email %>"/>
  <br>
  <INPUT TYPE="submit" value="Make Payment" class="ui green button"></td>
</form>

app/views/dashboard/_profile.html.haml
- @student = current_user
- @guardian = @student.guardian
- @current_step = @student.registration_form.current_step
- if current_user.payment_made
  .ui.center.aligned.segment.blue.inverted.segment
    Provisionl Rank List Status
    %table.ui.celled.structured.table
      %thead
        %tr
          %th Preference
          %th Choice
          %th Status
          %th Rank
      %tbody
        - Choice.where(student: current_user, disabled: false).each do |choice|
          %tr
            %td= choice.preference
            %td= choice.programme.name
            %td= choice.status
            %td= choice.rank
    .ui.message
      .header
        Notice
      .list
        %li Rank list may be subject to changes till final list is published on 5th June 2016
        %li Upload photo In the upload photo step to download the application form
- if @current_step > 1
  .step-2
    .ui.center.aligned.segment.blue.inverted.segment
      Personal Details
    .ui.stackable.two.column.grid
      .four.wide.column
        %label 1. Application Number
      .twelve.wide.column
        .ui.blue.segment
          ="MESMP16#{format('%04d', @student.id)}"
      .four.wide.column
        %label 1. Name
      .twelve.wide.column
        .ui.blue.segment
          = @student.name
    .ui.stackable.four.column.grid
      .column
        %label 2. Gender
        .ui.blue.segment
          = @student.gender
      .column
        %label 3. Blood Group
        .ui.blue.segment
          = @student.blood_group
      .column
        %label 4. Nationality
        .ui.blue.segment
          = @student.nationality.try(:name)
      .column
        %label 5. Religion
        .ui.blue.segment
          = @student.religion
      .four.wide.column
        %label 6. Community Category
        .ui.blue.segment
          = ReservationCategory.find_by_id(@student.reservation_category).try(:name)
      .four.wide.column
        %label 7.Caste
        .ui.blue.segment
          = @student.caste.try(:name)
      .four.wide.column
        %label 8. Date Of Birth
        .ui.blue.segment
          = @student.dob.try(:to_date).try { |d| d.strftime('%d-%m-%Y') }
      .four.wide.column
        %label 9. Place Of Birth
        .ui.blue.segment
          = @student.birth_place
    .ui.stackable.four.column.grid
      .column
        %label 10. Born in
        .ui.blue.segment
          = @student.born_in
      .column
        %label 11. Mobile No
        .ui.blue.segment
          = @student.mobile_no
      .column
        %label 12. Phone No
        .ui.blue.segment
          = @student.phone_no
      .column
        %label 15. Aadhar number
        .ui.blue.segment
          = @student.aadhar_no
- if @current_step > 2
  .step-3
    %table.ui.table.address
      %thead
        %tr
          %th.eight.wide Permanent Address
          %th.eight.wide Communication Address
      %tbody
        %tr
          %td
            = @student.address_line1
          %td.border
            = @student.comm_address_line1
        %tr
          %td
            = @student.address_line2
          %td.border
            = @student.comm_address_line2
        %tr
          %td
            = @student.post_office
          %td.border
            = @student.comm_post_office
        %tr
          %td
            = @student.taluk
          %td.border
            = @student.comm_taluk
        %tr
          %td
            = @student.district
          %td.border
            = @student.comm_district
        %tr
          %td
            = @student.state.try(:name)
          %td.border
            = @student.comm_state.try(:name)
        %tr
          %td
            = @student.pincode
          %td.border
            = @student.comm_pincode

        %tr
          %td
            = @student.country.try(:name)
          %td.border
            = @student.country.try(:name)
- if @current_step > 3
  .step-4
  .ui.stackable.segment.parent
    .ui.center.aligned.segment.blue.inverted.segment
      Parent Information
    .ui.stackable.four.column.grid
      .column
        %label
          Name Of Parent/Guarduan
        .ui.purple.segment
          = @guardian.try(:name)
      .column
        %label
          STD Code
        .ui.purple.segment
          0495
      .column
        %label
          Phone Number
        .ui.purple.segment
          = @guardian.try(:phone_no)
      .column
        %label
          Mobile
        .ui.purple.segment
          = @guardian.try(:mobile_no)
    .ui.stackable.four.column.grid
      .column
        %label
          Email
        .ui.purple.segment
          = @guardian.email
      .column
        %label
          Relationship With Applicant
        .ui.purple.segment
          = @guardian.try(:relationship)
      .column
        %label
          Occupation/Annual Income
        .ui.purple.segment
          = @guardian.occupation.try(:name)
          = @guardian.try(:annual_income)
      .column
        %label
          Phone No Of Local Guardian
        .ui.purple.segment
          = @guardian.try(:phone_no)

    .ui.two.column.middle.aligned.relaxed.fitted.stackable.grid
      .column
        .Parent-address
        %table.ui.table
          %thead
            %tr
              %th.eight.wide
                Parent/Guardian: Address
          %tbody
            %tr
              %td
                = @guardian.try(:address_line1)
            %tr
              %td
                = @guardian.try(:address_line2)
            %tr
              %td
                = @guardian.try(:post_office)
            %tr
              %td
                = @guardian.try(:district)
            %tr
              %td
                = @guardian.try(:pincode)

      .column
        .Parent-address
        %table.ui.table
          %thead
            %tr
              %th.eight.wide
                Parent/Guardian: Local Address
          %tbody
            %tr
              %td
                = @guardian.try(:address_line1)
            %tr
              %td
                = @guardian.try(:address_line2)
            %tr
              %td
                = @guardian.try(:post_office)
            %tr
              %td
                = @guardian.try(:district)
            %tr
              %td
                = @guardian.try(:pincode)
- if @current_step > 4
  .step-5
  .appl-mark
    .ui.stackable.segment.parent
      .ui.center.aligned.segment.blue.inverted.segment
        Weightages / Additional Information
      .ui.stackable.four.column.grid
        .column
          %label NSS Certificate Holder
          .ui.blue.segment
            = @student.nss ? "Yes" : "No"
        .column
          %label NCC certificate Holder
          .ui.blue.segment
            = @student.ncc
        .column
          %label Blind
          .ui.blue.segment
            = @student.blind ? "Yes" : "No"
        .column
          %label Deaf
          .ui.blue.segment
            = @student.deaf ? "Yes" : "No"
      .ui.stackable.two.column.grid
        .column
          %label Orthopedically Handicapped
          .ui.blue.segment
            = @student.orthopedic ? "Yes" : "No"
        .column
          %label Ex-service/Dependent of Ex-serviceman/Javan
          .ui.blue.segment
            = @student.ex_service ? "Yes" : "No"
      .ui.stackable.two.column.grid
        .column
          %label Have you got first place/A Grade in Arts Festival (National, District, State Level)?
          .ui.blue.segment
            = @student.arts ? "Yes" : "No"
        .column
          %label Have you got first place/A Grade in sports/games (National, District, State Level)?
          .ui.blue.segment
            = @student.sports ? "Yes" : "No"
      .ui.stackable.two.column.grid
        .column
          %label No of chances taken for passing the qualifying examination
          .ui.blue.segment
            = @student.no_of_chances
        .column
          %label Have you worked in the illiteracy eradication programme
          .ui.blue.segment
            = @student.illiteracy_eradication
- if @current_step > 5
  .step-6
  .appl-mark
    .ui.stackable.segment.parent
      .ui.center.aligned.segment.blue.inverted.segment
        Accadamic Details
      .ui.stackable.four.column.grid
        .four.wide.column
          %label 10. Education Board
          .ui.teal.segment
            = Board.find_by_id(Stream.find_by_id(StreamSubject.find_by_id(Mark.where(student: @student).first.try(:stream_subject_id)).try(:stream_id)).try(:board_id)).try(:name)
        .four.wide.column
          %label 11. Stream of study
          .ui.teal.segment
            = Stream.find_by_id(StreamSubject.find_by_id(Mark.where(student: @student).first.try(:stream_subject_id)).try(:stream_id)).try(:name)
        .four.wide.column
          %label 12. Institution Attended
          .ui.teal.segment
            = @student.twelfth_institution
        .four.wide.column
          %label 13. Year Of Study
          .ui.teal.segment
            = @student.twelfth_yos
        .four.wide.column
          %label 14. Year Of Passing
          .ui.teal.segment
            = @student.twelfth_yop
        .four.wide.column
          %label 15.Reg: No
          .ui.teal.segment
            = @student.twelfth_regno
        .four.wide.column
          %label 16. TC Date
          .ui.teal.segment
            = @student.twelfth_tc_date
        .four.wide.column
          %label 17. TC Number
          .ui.teal.segment
            = @student.twelfth_tc_no
      .appl-mark
      - subjects = []
      - subject_ids = []
      - marks = []
      - grades = []
      - Mark.where(student: @student).order(:stream_subject_id).each do |mark|
        - next if subject_ids.include? StreamSubject.find_by_id(mark.stream_subject_id).try(:id)
        - subject_ids << StreamSubject.find_by_id(mark.stream_subject_id).try(:id)
        - subjects << StreamSubject.find_by_id(mark.stream_subject_id).try(:name)
        - marks << mark.score
        - grades << mark.grade
      %table.ui.celled.structured.table
        %thead
          %tr
            %th Details Of Marks
            - subjects.each do |subject|
              %th= subject
        %tbody
          / %tr
          /   %td Grade
          /   - grades.each do |grade|
          /     %td= grade
          %tr
            %td Mark Scored
            - marks.each do |mark|
              %td= mark
- if @current_step > 6
  - choices = []
  - Choice.where(student: @student).order(:preference).each do |choice|
    - next if choices.include? Programme.find_by_id(choice.try(:programme_id)).try(:name)
    - choices << Programme.find_by_id(choice.programme_id).try(:name)
  .step-7
    .appl-mark
      .ui.stackable.segment.parent
        .ui.center.aligned.segment.blue.inverted.segment
          Course Preferences
        .ui.stackable.five.column.grid
          - choices.each_with_index do |choice, i|
            .column
              %label
                = "Choice #{i+1}"
              .ui.blue.segment
                = choice
=# render "layouts/welcome"
-# = render 'users/max_enabled_info'

app/views/dashboard/address.html.haml
%h1 Student Addresses

= form_for current_user, html:{class:"ui fluid form"}, remote:true do |f|
  #error_messages
  = hidden_field_tag 'step_name', 'Address'
  .field
    .ui.segment.black.required.field
      %label Permanent Address
      .required.field
        = f.text_field :address_line1, placeholder: "Address Line 1", class: "permanent address line1"
        .label.indication
          %i.warning.circle.icon
          Enter your address (eg:- House Name)
      .required.afield
        = f.text_field :address_line2, placeholder: "Address Line 2", class: "permanent address line2"
        .label.indication
          %i.warning.circle.icon
          Enter your address 2 (eg:- Street Name)
      .two.fields
        .required.field
          = f.collection_select :country_id, Country.all, :id, :name, { include_blank: true }, {class: 'ui search permanent countries dropdown'}
          .label.indication
            %i.warning.circle.icon
            Select your Country
        .required.field
          = f.select :state_id, options_from_collection_for_select(State.all, :id, :name, current_user.state_id), {include_blank: true}, {class: "ui search permanent states dropdown", placeholder: "State"}
          .label.indication
            %i.warning.circle.icon
            Select your State
      .two.fields
        .required.field
          = f.select :district_id, options_from_collection_for_select(District.all, :id, :name, current_user.district_id), {include_blank: true}, {class: "ui search permanent districts dropdown", placeholder: "District"}
          .label.indication
            %i.warning.circle.icon
            Select your District
        .required.field
          = f.text_field :taluk, placeholder: "Taluk", class: "permanent taluk"
          .label.indication
            %i.warning.circle.icon
            Enter your Taluk
      .two.fields
        .required.field
          = f.text_field :post_office, placeholder: "Post Office", class: "permanent post office"
          .label.indication
            %i.warning.circle.icon
            Enter your Post Office
        .required.field
          = f.text_field :pincode, placeholder: "Pincode", class: "permanent pincode"
          .label.indication
            %i.warning.circle.icon
            Enter your Pincode
      .field
        .ui.divider
        .ui.communication.checkbox
          = f.check_box :same_address
          = f.label "Copy Permanent Address to Communication Address"

    .ui.communication.segment.black.required.field
      %label Communication Address
      .required.field
        = f.text_field :comm_address_line1, placeholder: "Address Line 1", class: "communication address line1"
        .label.indication
          %i.warning.circle.icon
          Enter your address (eg:- House Name)
      .required.field
        = f.text_field :comm_address_line2, placeholder: "Address Line 2", class: "communication address line2"
        .label.indication
          %i.warning.circle.icon
          Enter your address  (eg:- Street Name)
      .two.fields
        .required.field
          = f.select :comm_country_id, options_from_collection_for_select(Country.all, :id, :name, current_user.comm_country_id), {include_blank: true}, {class: 'ui search communication countries dropdown'}
          .label.indication
            %i.warning.circle.icon
            Select your Country
        .required.field
          = f.select :comm_state_id, options_from_collection_for_select(State.all, :id, :name, current_user.comm_state_id), {include_blank: true}, {class: "ui search communication states dropdown", placeholder: "State"}
          .label.indication
            %i.warning.circle.icon
            Select your State
      .two.fields
        .required.field
          = f.select :comm_district_id, options_from_collection_for_select(District.all, :id, :name, current_user.comm_district_id), {include_blank: true}, {class: "ui search communication districts dropdown", placeholder: "District"}
          .label.indication
            %i.warning.circle.icon
            Select your District
        .required.field
          = f.text_field :comm_taluk, placeholder: "Taluk", class: "communication taluk"
          .label.indication
            %i.warning.circle.icon
            Enter your Taluk
      .two.fields
        .required.field
          = f.text_field :comm_post_office, placeholder: "Post Office", class: "communication post office"
          .label.indication
            %i.warning.circle.icon
            Enter your Post Office
        .required.field
          = f.text_field :comm_pincode, placeholder: "Pincode", class: "communication pincode"
          .label.indication
            %i.warning.circle.icon
            Enter your Pincode
  .field
    = f.submit 'Save & Proceed', class: "ui submit proceed button" unless current_user.submission_done

app/views/dashboard/education.html.haml
%h1 Education Information

= form_for current_user, html:{class:'ui fluid form'}, remote:true do |f|
  #error_messages
  = hidden_field_tag 'step_name', 'Education'
  .field
    .two.fields
      .required.field
        = f.label :board_id
        = f.select :board_id, options_from_collection_for_select(Board.all, :id, :name, current_user.board_id), {include_blank: true}, {class: 'ui search boards dropdown'}
        .label.indication
          %i.warning.circle.icon
          Board of study
      .required.field
        = f.label :stream_id
        = f.select :stream_id, options_from_collection_for_select(Stream.all, :id, :name, current_user.stream_id), {include_blank: true}, {class: 'ui search streams dropdown'}
        .label.indication
          %i.warning.circle.icon
          Stream of study
    .field
    .ui.black.secondary.segment
      %h4{class:"ui header"} 10th STD Details
      .ui.stackable.four.column.grid
        .column
          = label_tag "Year of study"
          .ui.input
            = f.text_field :tenth_yos, placeholder: "year of study..."
        .column
          = label_tag  :year_of_passing
          .ui.input
            = f.text_field :tenth_yop, placeholder: "Year of passing..."
        .column
          = label_tag  "Register Number"
          .ui.input
            = f.text_field :tenth_regno, placeholder: "Register no..."
        .column
          = label_tag "Institution attended"
          .ui.input
            = f.text_field :tenth_institution, placeholder: "Enter your school..."
    .ui.black.secondary.segment
      %h4{class:"ui header"} +2 Details
      .ui.stackable.three.column.grid
        .row
          .column
            = label_tag "Year of study"
            .ui.fluid.icon.input
              = f.text_field :twelfth_yos, placeholder: "year of study..."
          .column
            = label_tag  :year_of_passing
            .ui.fluid.icon.input
              = f.text_field :twelfth_yop, placeholder: "Year of passing..."
          .column
            = label_tag  "Register Number"
            .ui.fluid.icon.input
              = f.text_field :twelfth_regno, placeholder: "Register no..."
        .row
          .column
            = label_tag "Institution attended"
            .ui.fluid.icon.input
              = f.text_field :twelfth_institution, placeholder: "Enter your school..."
          .column
            = label_tag "TC Number"
            .ui.fluid.icon.input
              = f.text_field :twelfth_tc_no, placeholder: "tc number..."
          .column
            = label_tag "TC. Date specified"
            .ui.input
              = f.text_field :twelfth_tc_date, placeholder: "tc date..."


    .field
    = f.submit 'Save & Proceed', class: "ui submit proceed button" unless current_user.submission_done

app/views/dashboard/index.html.haml
= render 'profile'
%big
  %b
    Read
    = link_to "INSTRUCTIONS", dashboard_instructions_path
    to get started.

app/views/dashboard/instructions.html.haml
.ui.red.inverted.segment
  Instructions
.segment
  .row
    = render 'shared/instructions'
  - if current_user.registration_form.instructions_read == false
    - info_text = 'Read and understood all instructions.'
  - else
    - info_text = 'Take me to the form'
  .ui.row
    .row
      = button_to info_text, { :action => 'instructions'}, remote:true, class: "ui positive submit proceed button"

app/views/dashboard/marks.html.haml
- subject_structure = current_user.reload.board.subject_structure
- @subject_structure = subject_structure.split(',').map{ |part| part.to_i }
- @total_parts = @subject_structure.count
- @subjects = []
- 1.upto(@total_parts) do |part_number|
  - @subjects << StreamSubject.where(stream_id: current_user.stream_id, part: part_number)
- @total_subjects = @subject_structure.sum

- @stream_subjects = []
- @marks = []
- @max_marks = []
- Mark.where(student_id: current_user.id).each do |mark|
  - @stream_subjects[mark.subject_position] = mark.stream_subject_id
  - @marks[mark.subject_position] = mark.score
  - @max_marks[mark.subject_position] = mark.stream_subject.try(:max_marks)

- if current_user.payment_made

  %h1 Mark List

  = form_for current_user, html:{class:"ui fluid form"}, remote:true do |f|
    #error_messages
    = hidden_field_tag 'step_name', 'Marks'
    .field
      .ui.inverted.red.button#markmore Instructions
    %br
    .ui.center.aligned.segment.teal.inverted.segment
      Mark Sheet
    %br
    .ui.stackable.four.column.grid
    %table.ui.celled.structured.table
      %thead
        %tr
          %th{rowspan: "2"} Details Of Marks
          - 'A'.upto(('A'.ord + @total_parts - 1).chr).each do |part|
            %th{colspan: @subject_structure[part.ord - 'A'.ord]}
              = "Part #{part}"
        %tr
          - index = 0
          - @subject_structure.each_with_index do |subject_count, part_number|
            - @subjects = StreamSubject.where(stream_id: current_user.stream_id, part: part_number + 1)
            - 0.upto(subject_count - 1) do
              %th.modified_table
                = select_tag "student[subject_params][#{index}][stream_subject_id]", options_for_select(@subjects.map{ |subject| [subject.name, subject.id, { 'data-max-marks' => subject.max_marks}] }, @stream_subjects[index]), {include_blank: 'Subject', :id => "subject_#{index}", class: "ui subjects dropdown modified_dropdown"}
              - index += 1
      %tbody
        %tr
          %td Marks Obtained
          - 0.upto(@total_subjects - 1) do |index|
            %td
              .ui.icon.input
                = text_field_tag "student[subject_params][#{index}][score]", nil, value:@marks[index] || 0, :id => "mark_#{index}", :class => "modified_column marks ui icon input"
        %tr
          %td Maximum Marks
          - 0.upto(@total_subjects - 1) do |index|
            %td
              .ui.icon.input
                %input{disabled: true, :type => "text" ,:class => "modified_column max-marks ui icon input",value: "#{@max_marks[index] || 0}", :readonly => "",:id => "max_mark_#{index}"}
                  %i.inverted.search.icon
    .field
      = submit_tag 'Save & Proceed', class: "ui submit button" unless current_user.submission_done
      = render 'dashboard/mark_instructions'
- else
  = render 'shared/payment_terms'

  %br
  A payment of 100.00 + Transaction Fees for SC/ST students and 150.00 + Transaction Fees for others are required to continue.
  = render 'dashboard/payment'