config/routes.rb
Rails.application.routes.draw do
  get 'reports/consolidated_report_selection'
  post 'reports/consolidated_report'
  get 'reports/index_marks'
  post 'reports/generate_index_pdf'

  resources :choices
  resources :programmes
  resources :boards, shallow: true do
    resources :streams do
      resources :stream_subjects
    end
  end
  resources :guardians
  resources :occupations
  resources :qualifications
  resources :countries, shallow: true do
    resources :states do
      resources :districts
    end
  end
  resources :reservation_categories do
    resources :castes
  end
  resources :registration_forms
  resources :registration_steps
  resources :students

  get '/login' => 'sessions#new', as: :root
  get '/auth/:provider/callback' => 'sessions#create'
  post '/transaction/ccavRequestHandler'=> 'sessions#ccavRequestHandler'
  post '/transaction/ccavResponseHandler'=> 'sessions#ccavResponseHandler'
  delete '/auth/logout' => 'sessions#destroy'

  namespace :dashboard do
    get 'index'
    match 'instructions', via: [:get, :post]
    get 'personal'
    get 'address'
    get 'guardian'
    get 'weightages'
    get 'education'
    get 'payment'
    get 'marks'
    get 'choices'
    get 'submission'
    get 'photo_upload'
    get 'generate_application_pdf'
    get 'submission_done'
    get 'phase_completed'
    get 'update_menu'
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :streams
end

app/models/caste.rb
class Caste < ActiveRecord::Base
  belongs_to :reservation_category
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :student
  belongs_to :programme
end

app/models/configurator.rb
class Configurator < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :state

  def to_s
    self.name
  end
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  belongs_to :student
  belongs_to :qualification
  belongs_to :occupation
  belongs_to :country
  belongs_to :state
  belongs_to :district

  before_validation :check_if_same_address

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.#{field} = self.student.#{field}")
        end
      end
    end
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :stream_subject
  belongs_to :mark
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/programme.rb
class Programme < ActiveRecord::Base
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :districts
  belongs_to :country
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :stream_subjects
  belongs_to :board
  has_many :choices
end

app/models/stream_subject.rb
class StreamSubject < ActiveRecord::Base
  belongs_to :stream
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :registration_form
  belongs_to :nationality, foreign_key: "nationality_id", class_name: "Country"
  has_one :guardian
  belongs_to :reservation_category
  belongs_to :caste
  belongs_to :state
  belongs_to :district
  belongs_to :country
  belongs_to :comm_state, foreign_key: "comm_state_id", class_name: "State"
  belongs_to :comm_district, foreign_key: "comm_district_id", class_name: "District"
  belongs_to :board
  belongs_to :stream
  mount_uploader :profile_image, ImageUploader

  before_validation :check_if_same_address

  def subject_params=(subject_params)
    subject_params.each do |mark_details|
      mark = mark_details[1]
      unless mark[:score] == 0
        @mark = Mark.where(student_id: self.id, subject_position: mark_details[0]).first
        if @mark
          @mark.update(score: mark[:score], stream_subject_id: mark[:stream_subject_id])
        else
          Mark.create(student_id: self.id, stream_subject_id: mark[:stream_subject_id], score: mark[:score], subject_position:mark_details[0])
        end
      end
    end
  end

  def choice_params=(choice_params)
    choice_params.each do |choice|
      preference_no = choice[0].gsub("choice_", "").to_i
      programme_id = choice[1]

      @choice = Choice.where(preference: preference_no, student_id: self.id).first
      if @choice
        @choice.update(programme_id: programme_id)
      else
        Choice.create(preference: preference_no, student_id: self.id, programme_id: programme_id)
      end
    end
  end

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.comm_#{field} = self.#{field}")
        end
      end
    end
end

app/controllers/stream_subjects_controller.rb
class StreamSubjectsController < ApplicationController
  before_action :set_stream, except: [:show, :edit, :update, :destroy]
  before_action :set_stream_subject, only: [:show, :edit, :update, :destroy]

  # GET streams/1/stream_subjects
  def index
    @stream_subjects = @stream.stream_subjects
  end

  # GET streams/1/stream_subjects/1
  def show
  end

  # GET streams/1/stream_subjects/new
  def new
    @stream_subject = @stream.stream_subjects.build
  end

  # GET streams/1/stream_subjects/1/edit
  def edit
  end

  # POST streams/1/stream_subjects
  def create
    @stream_subject = @stream.stream_subjects.build(stream_subject_params)

    if @stream_subject.save
      redirect_to(@stream_subject.stream, notice: 'Stream subject was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT streams/1/stream_subjects/1
  def update
    if @stream_subject.update_attributes(stream_subject_params)
      redirect_to(@stream_subject, notice: 'Stream subject was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE streams/1/stream_subjects/1
  def destroy
    @stream_subject.destroy

    redirect_to stream_stream_subjects_url(@stream_subject.stream)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:stream_id])
    end

    def set_stream_subject
      @stream_subject = StreamSubject.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stream_subject_params
      params.require(:stream_subject).permit(:name, :part, :max_marks)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/castes_helper.rb
module CastesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stream_subjects_helper.rb
module StreamSubjectsHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/stream_subjects/_form.html.haml
= form_for [@stream, @stream_subject] do |f|
  -if @stream_subject.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stream_subject.errors.count, "error")} prohibited this stream_subject from being saved:"
      %ul
        - @stream_subject.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :part
    = f.number_field :part
  .field
    = f.label :max_marks
    = f.number_field :max_marks
  .actions
    = f.submit 'Save'

app/views/stream_subjects/edit.html.haml
%h1 Editing stream_subject

= render 'form'

= link_to 'Show', @stream_subject
\|
= link_to 'Back', stream_stream_subjects_path(@stream_subject.stream)

app/views/stream_subjects/index.html.haml
%h1 Listing stream_subjects

%table
  %tr
    %th Name
    %th Part
    %th Max marks
    %th
    %th
    %th

  - @stream_subjects.each do |stream_subject|
    %tr
      %td= stream_subject.name
      %td= stream_subject.part
      %td= stream_subject.max_marks
      %td= link_to 'Show', stream_subject
      %td= link_to 'Edit', edit_stream_subject_path(stream_subject)
      %td= link_to 'Destroy', stream_subject, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Stream subject', new_stream_stream_subject_path(params[:stream_id])

app/views/stream_subjects/new.html.haml
%h1 New stream_subject

= render 'form'

= link_to 'Back', stream_stream_subjects_path(@stream_subject.stream)

app/views/stream_subjects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @stream_subject.name
%p
  %b Part:
  = @stream_subject.part
%p
  %b Max marks:
  = @stream_subject.max_marks

= link_to 'Edit', edit_stream_subject_path(@stream_subject)
\|
= link_to 'Back', stream_stream_subjects_path(@stream_subject.stream)