config/routes.rb
Rails.application.routes.draw do
  get 'reports/consolidated_report_selection'
  post 'reports/consolidated_report'
  get 'reports/index_marks'
  post 'reports/generate_index_pdf'

  resources :choices
  resources :programmes
  resources :boards, shallow: true do
    resources :streams do
      resources :stream_subjects
    end
  end
  resources :guardians
  resources :occupations
  resources :qualifications
  resources :countries, shallow: true do
    resources :states do
      resources :districts
    end
  end
  resources :reservation_categories do
    resources :castes
  end
  resources :registration_forms
  resources :registration_steps
  resources :students

  get '/login' => 'sessions#new', as: :root
  get '/auth/:provider/callback' => 'sessions#create'
  post '/transaction/ccavRequestHandler'=> 'sessions#ccavRequestHandler'
  post '/transaction/ccavResponseHandler'=> 'sessions#ccavResponseHandler'
  delete '/auth/logout' => 'sessions#destroy'

  namespace :dashboard do
    get 'index'
    match 'instructions', via: [:get, :post]
    get 'personal'
    get 'address'
    get 'guardian'
    get 'weightages'
    get 'education'
    get 'payment'
    get 'marks'
    get 'choices'
    get 'submission'
    get 'photo_upload'
    get 'generate_application_pdf'
    get 'submission_done'
    get 'phase_completed'
    get 'update_menu'
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :streams
end

app/models/caste.rb
class Caste < ActiveRecord::Base
  belongs_to :reservation_category
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :student
  belongs_to :programme
end

app/models/configurator.rb
class Configurator < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :state

  def to_s
    self.name
  end
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  belongs_to :student
  belongs_to :qualification
  belongs_to :occupation
  belongs_to :country
  belongs_to :state
  belongs_to :district

  before_validation :check_if_same_address

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.#{field} = self.student.#{field}")
        end
      end
    end
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :stream_subject
  belongs_to :mark
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/programme.rb
class Programme < ActiveRecord::Base
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :districts
  belongs_to :country
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :stream_subjects
  belongs_to :board
  has_many :choices
end

app/models/stream_subject.rb
class StreamSubject < ActiveRecord::Base
  belongs_to :stream
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :registration_form
  belongs_to :nationality, foreign_key: "nationality_id", class_name: "Country"
  has_one :guardian
  belongs_to :reservation_category
  belongs_to :caste
  belongs_to :state
  belongs_to :district
  belongs_to :country
  belongs_to :comm_state, foreign_key: "comm_state_id", class_name: "State"
  belongs_to :comm_district, foreign_key: "comm_district_id", class_name: "District"
  belongs_to :board
  belongs_to :stream
  mount_uploader :profile_image, ImageUploader

  before_validation :check_if_same_address

  def subject_params=(subject_params)
    subject_params.each do |mark_details|
      mark = mark_details[1]
      unless mark[:score] == 0
        @mark = Mark.where(student_id: self.id, subject_position: mark_details[0]).first
        if @mark
          @mark.update(score: mark[:score], stream_subject_id: mark[:stream_subject_id])
        else
          Mark.create(student_id: self.id, stream_subject_id: mark[:stream_subject_id], score: mark[:score], subject_position:mark_details[0])
        end
      end
    end
  end

  def choice_params=(choice_params)
    choice_params.each do |choice|
      preference_no = choice[0].gsub("choice_", "").to_i
      programme_id = choice[1]

      @choice = Choice.where(preference: preference_no, student_id: self.id).first
      if @choice
        @choice.update(programme_id: programme_id)
      else
        Choice.create(preference: preference_no, student_id: self.id, programme_id: programme_id)
      end
    end
  end

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.comm_#{field} = self.#{field}")
        end
      end
    end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choices
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET students/1/choices
  def index
    @choices = @student.choices
  end

  # GET students/1/choices/1
  def show
  end

  # GET students/1/choices/new
  def new
    @choice = @student.choices.build
  end

  # GET students/1/choices/1/edit
  def edit
  end

  # POST students/1/choices
  def create
    @choice = @student.choices.build(choice_params)

    if @choice.save
      redirect_to([@choice.student, @choice], notice: 'Choice was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT students/1/choices/1
  def update
    if @choice.update_attributes(choice_params)
      redirect_to([@choice.student, @choice], notice: 'Choice was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE students/1/choices/1
  def destroy
    @choice.destroy

    redirect_to student_choices_url(@student)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choices
      @student = Student.find(params[:student_id])
    end

    def set_choice
      @choice = @student.choices.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def choice_params
      params.require(:choice).permit(:preference, :programme_id, :index_mark, :rank, :status, :general, :sc, :st, :muslim, :handicapped, :obc, :obh, :etb, :latin, :disabled)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/castes_helper.rb
module CastesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/choices/_form.html.haml
= form_for [@choice.student, @choice] do |f|
  -if @choice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@choice.errors.count, "error")} prohibited this choice from being saved:"
      %ul
        - @choice.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :preference
    = f.number_field :preference
  .field
    = f.label :programme
    = f.text_field :programme
  .field
    = f.label :index_mark
    = f.text_field :index_mark
  .field
    = f.label :rank
    = f.number_field :rank
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :general
    = f.text_field :general
  .field
    = f.label :sc
    = f.text_field :sc
  .field
    = f.label :st
    = f.text_field :st
  .field
    = f.label :muslim
    = f.text_field :muslim
  .field
    = f.label :handicapped
    = f.text_field :handicapped
  .field
    = f.label :obc
    = f.text_field :obc
  .field
    = f.label :obh
    = f.text_field :obh
  .field
    = f.label :etb
    = f.text_field :etb
  .field
    = f.label :latin
    = f.text_field :latin
  .field
    = f.label :disabled
    = f.check_box :disabled
  .actions
    = f.submit 'Save'

app/views/choices/edit.html.haml
%h1 Editing choice

= render 'form'

= link_to 'Show', [@choice.student, @choice]
\|
= link_to 'Back', student_choices_path(@choice.student)

app/views/choices/index.html.haml
%h1 Listing choices

%table
  %tr
    %th Preference
    %th Programme
    %th Index mark
    %th Rank
    %th Status
    %th General
    %th Sc
    %th St
    %th Muslim
    %th Handicapped
    %th Obc
    %th Obh
    %th Etb
    %th Latin
    %th Disabled
    %th
    %th
    %th

  - @choices.each do |choice|
    %tr
      %td= choice.preference
      %td= choice.programme
      %td= choice.index_mark
      %td= choice.rank
      %td= choice.status
      %td= choice.general
      %td= choice.sc
      %td= choice.st
      %td= choice.muslim
      %td= choice.handicapped
      %td= choice.obc
      %td= choice.obh
      %td= choice.etb
      %td= choice.latin
      %td= choice.disabled
      %td= link_to 'Show', [choice.student, choice]
      %td= link_to 'Edit', edit_student_choice_path(choice.student, choice)
      %td= link_to 'Destroy', [choice.student, choice], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Choice', new_student_choice_path(params[:student_id])

app/views/choices/new.html.haml
%h1 New choice

= render 'form'

= link_to 'Back', student_choices_path(@choice.student)

app/views/choices/show.html.haml
%p#notice= notice

%p
  %b Preference:
  = @choice.preference
%p
  %b Programme:
  = @choice.programme
%p
  %b Index mark:
  = @choice.index_mark
%p
  %b Rank:
  = @choice.rank
%p
  %b Status:
  = @choice.status
%p
  %b General:
  = @choice.general
%p
  %b Sc:
  = @choice.sc
%p
  %b St:
  = @choice.st
%p
  %b Muslim:
  = @choice.muslim
%p
  %b Handicapped:
  = @choice.handicapped
%p
  %b Obc:
  = @choice.obc
%p
  %b Obh:
  = @choice.obh
%p
  %b Etb:
  = @choice.etb
%p
  %b Latin:
  = @choice.latin
%p
  %b Disabled:
  = @choice.disabled

= link_to 'Edit', edit_student_choice_path(@choice.student, @choice)
\|
= link_to 'Back', student_choices_path(@choice.student)