config/routes.rb
Rails.application.routes.draw do
  get 'reports/consolidated_report_selection'
  post 'reports/consolidated_report'
  get 'reports/index_marks'
  post 'reports/generate_index_pdf'

  resources :choices
  resources :programmes
  resources :boards, shallow: true do
    resources :streams do
      resources :stream_subjects
    end
  end
  resources :guardians
  resources :occupations
  resources :qualifications
  resources :countries, shallow: true do
    resources :states do
      resources :districts
    end
  end
  resources :reservation_categories do
    resources :castes
  end
  resources :registration_forms
  resources :registration_steps
  resources :students

  get '/login' => 'sessions#new', as: :root
  get '/auth/:provider/callback' => 'sessions#create'
  post '/transaction/ccavRequestHandler'=> 'sessions#ccavRequestHandler'
  post '/transaction/ccavResponseHandler'=> 'sessions#ccavResponseHandler'
  delete '/auth/logout' => 'sessions#destroy'

  namespace :dashboard do
    get 'index'
    match 'instructions', via: [:get, :post]
    get 'personal'
    get 'address'
    get 'guardian'
    get 'weightages'
    get 'education'
    get 'payment'
    get 'marks'
    get 'choices'
    get 'submission'
    get 'photo_upload'
    get 'generate_application_pdf'
    get 'submission_done'
    get 'phase_completed'
    get 'update_menu'
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :streams
end

app/models/caste.rb
class Caste < ActiveRecord::Base
  belongs_to :reservation_category
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :student
  belongs_to :programme
end

app/models/configurator.rb
class Configurator < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :state

  def to_s
    self.name
  end
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  belongs_to :student
  belongs_to :qualification
  belongs_to :occupation
  belongs_to :country
  belongs_to :state
  belongs_to :district

  before_validation :check_if_same_address

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.#{field} = self.student.#{field}")
        end
      end
    end
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :stream_subject
  belongs_to :mark
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/programme.rb
class Programme < ActiveRecord::Base
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
end

app/models/registration_step.rb
class RegistrationStep < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :districts
  belongs_to :country
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :stream_subjects
  belongs_to :board
  has_many :choices
end

app/models/stream_subject.rb
class StreamSubject < ActiveRecord::Base
  belongs_to :stream
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :registration_form
  belongs_to :nationality, foreign_key: "nationality_id", class_name: "Country"
  has_one :guardian
  belongs_to :reservation_category
  belongs_to :caste
  belongs_to :state
  belongs_to :district
  belongs_to :country
  belongs_to :comm_state, foreign_key: "comm_state_id", class_name: "State"
  belongs_to :comm_district, foreign_key: "comm_district_id", class_name: "District"
  belongs_to :board
  belongs_to :stream
  mount_uploader :profile_image, ImageUploader

  before_validation :check_if_same_address

  def subject_params=(subject_params)
    subject_params.each do |mark_details|
      mark = mark_details[1]
      unless mark[:score] == 0
        @mark = Mark.where(student_id: self.id, subject_position: mark_details[0]).first
        if @mark
          @mark.update(score: mark[:score], stream_subject_id: mark[:stream_subject_id])
        else
          Mark.create(student_id: self.id, stream_subject_id: mark[:stream_subject_id], score: mark[:score], subject_position:mark_details[0])
        end
      end
    end
  end

  def choice_params=(choice_params)
    choice_params.each do |choice|
      preference_no = choice[0].gsub("choice_", "").to_i
      programme_id = choice[1]

      @choice = Choice.where(preference: preference_no, student_id: self.id).first
      if @choice
        @choice.update(programme_id: programme_id)
      else
        Choice.create(preference: preference_no, student_id: self.id, programme_id: programme_id)
      end
    end
  end

  protected
    def check_if_same_address
      if self.same_address
        address_fields = ['address_line1', 'address_line2', 'country_id', 'state_id',
           'district_id', 'taluk', 'post_office', 'pincode']
        address_fields.each do |field|
          eval("self.comm_#{field} = self.#{field}")
        end
      end
    end
end

app/controllers/registration_steps_controller.rb
class RegistrationStepsController < ApplicationController
  before_action :set_registration_step, only: [:show, :edit, :update, :destroy]

  # GET /registration_steps
  # GET /registration_steps.json
  def index
    @registration_steps = RegistrationStep.all
  end

  # GET /registration_steps/1
  # GET /registration_steps/1.json
  def show
  end

  # GET /registration_steps/new
  def new
    @registration_step = RegistrationStep.new
  end

  # GET /registration_steps/1/edit
  def edit
  end

  # POST /registration_steps
  # POST /registration_steps.json
  def create
    @registration_step = RegistrationStep.new(registration_step_params)

    respond_to do |format|
      if @registration_step.save
        format.html { redirect_to @registration_step, notice: 'Registration step was successfully created.' }
        format.json { render :show, status: :created, location: @registration_step }
      else
        format.html { render :new }
        format.json { render json: @registration_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_steps/1
  # PATCH/PUT /registration_steps/1.json
  def update
    respond_to do |format|
      if @registration_step.update(registration_step_params)
        format.html { redirect_to @registration_step, notice: 'Registration step was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_step }
      else
        format.html { render :edit }
        format.json { render json: @registration_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_steps/1
  # DELETE /registration_steps/1.json
  def destroy
    @registration_step.destroy
    respond_to do |format|
      format.html { redirect_to registration_steps_url, notice: 'Registration step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_step
      @registration_step = RegistrationStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_step_params
      params.require(:registration_step).permit(:position, :name, :icon, :url)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/castes_helper.rb
module CastesHelper
end

app/helpers/registration_steps_helper.rb
module RegistrationStepsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/registration_steps/_form.html.haml
= form_for @registration_step do |f|
  - if @registration_step.errors.any?
    #error_explanation
      %h2= "#{pluralize(@registration_step.errors.count, "error")} prohibited this registration_step from being saved:"
      %ul
        - @registration_step.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :position
    = f.number_field :position
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :icon
    = f.text_field :icon
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/registration_steps/edit.html.haml
%h1 Editing registration_step

= render 'form'

= link_to 'Show', @registration_step
\|
= link_to 'Back', registration_steps_path

app/views/registration_steps/index.html.haml
%h1 Listing registration_steps

%table
  %thead
    %tr
      %th Position
      %th Name
      %th Icon
      %th Url
      %th
      %th
      %th

  %tbody
    - @registration_steps.each do |registration_step|
      %tr
        %td= registration_step.position
        %td= registration_step.name
        %td= registration_step.icon
        %td= registration_step.url
        %td= link_to 'Show', registration_step
        %td= link_to 'Edit', edit_registration_step_path(registration_step)
        %td= link_to 'Destroy', registration_step, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Registration step', new_registration_step_path

app/views/registration_steps/new.html.haml
%h1 New registration_step

= render 'form'

= link_to 'Back', registration_steps_path

app/views/registration_steps/show.html.haml
%p#notice= notice

%p
  %b Position:
  = @registration_step.position
%p
  %b Name:
  = @registration_step.name
%p
  %b Icon:
  = @registration_step.icon
%p
  %b Url:
  = @registration_step.url

= link_to 'Edit', edit_registration_step_path(@registration_step)
\|
= link_to 'Back', registration_steps_path